# Generated by Django 6.0.2 on 2026-04-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bakery_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
