# Generated by Django 6.0.2 on 2026-04-11 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bakery_app', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
