# Generated by Django 6.0.2 on 2026-04-11 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bakery_app', '0003_catalog_stock'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catalog',
            new_name='Product',
        ),
    ]
