# Generated by Django 6.0.2 on 2026-04-15 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bakery_app', '0004_rename_catalog_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='photo',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
    ]
